### ISSUE TITLE
PhysioNet Challenge issue

### ISSUE THREAD

**Issue by maystroh** [awni/ecg#20]
I run the example of PhysioNet challenge I got this error:

```
Traceback (most recent call last):
  File "build_datasets.py", line 48, in <module>
    dataset = load_all(data_path)
  File "build_datasets.py", line 26, in load_all
    dataset.append((ecg_file, [label]*num_labels))
TypeError: can't multiply sequence by non-int of type 'float'
```
I believe this issue is coming from the fact that we cant multiply a float with a list of strings.. instead we can multiple an int with a list of strings. Should I cast it the num_labels to int? or it is related to something how I'm reading the ECG file?

Thanks in advance.

**Comment by awni** [comment]
This is probably a python 2 vs python 3 thing (the code is only tested in 2.7). Yes you can simply cast num_lables to an int.
