### ISSUE TITLE
How can I get access to the full training dataset?

### ISSUE THREAD

**Issue by labiy** [awni/ecg#21]
Hello.
I noticed that "We build a dataset with more than 500 times the number of unique patients than previously studied corpora." 
So how to get this wonderful dataset, please help me.

**Comment by jackycsie** [comment]
https://irhythm.github.io/cardiol_test_set/

**Comment by physhik** [comment]
Download the file at https://irhythm.github.io/cardiol_test_set/

and after executing build_dataset.py file

and save this file at examples/irhythm directory and execute it.

https://gist.github.com/physhik/d0b1d2899118ae95ae898acf957b9490

**Comment by physhik** [comment]
Download the file at https://irhythm.github.io/cardiol_test_set/
and after executing build_dataset.py file
and save this file at examples/irhythm directory and execute it.
https://gist.github.com/physhik/d0b1d2899118ae95ae898acf957b9490

**Comment by physhik** [comment]
You need to customize examples/irhythm/build_dataset.py 

For example, 
data_dir = # your own data directory

and for epi_ext, need to attach * such as epi_ext='*.episodes.json'  and so on

**Comment by awni** [comment]
**Our data availability statement:**

The test dataset used to support the findings of this study is publicly available at https://irhythm.github.io/cardiol_test_set without restriction. Restrictions apply to the availability of the training dataset, which was used under license from iRhythm Technologies, Inc. for the current study. iRhythm Technologies, Inc. will consider requests to access the training data on an individual basis. Any data use will be restricted to noncommercial research purposes, and the data will only be made available on execution of appropriate data use agreements.

**Comment by king-no-crown** [comment]
> 您需要自定义https://github.com/awni/ecg/blob/master/examples/irhythm/build_datasets.py
> 
> 例如，
> data_dir =＃您自己的数据目录，
> 并将数据集拆分为批处理和其他子目录
> 
> 对于epi_ext，需要附加*，例如epi_ext ='*。episodes.json'等

请问一下，我创建的测试集为什么是空的？

**Comment by chenghunghsu** [comment]
I want to know where the file such as "kids_blacklist" and "vf_blacklist" in the file download from https://irhythm.github.io/cardiol_test_set/, I can't find them

**Comment by matru** [comment]
@physhik 

`You need to customize https://github.com/awni/ecg/blob/master/examples/irhythm/build_datasets.py

For example,
data_dir = # your own data directory
and split dataset into batches and other subdirectories

and for epi_ext, need to attach * such as epi_ext='*.episodes.json' and so on`

When you say split data into batches, what do you mean? The Cardiol set structure is:

`
This dataset contains 328, 30sec strips of ECG captured at 200 Hz. Each ECG file is saved in int16 binary format. Filenames ending in _grp[0-2] are reference labels, which are annotated by a group of cardiologists. In addition to reference files, each ECG strip also has 6 additional labels, with filenames ending in _rev[0-5] that correspond to 6 individual cardiologists annotating the data separately. Annotation files are saved in json format, with the list of rhythms saved under an "episodes" key.`

So under irhythm folder I also made:
```

 ./data/batches/kids_blacklist
 ./data/batches/vf_blacklist
 ./data/label_review/CARDIOL_MAY_2017
 ./data/label_review/CARDIOL_MAY_2017/CARDIOL_UNIQ_P
```

At top level of /data folder these subfolders exists, along with all the data sets .ecg/json files, what is the proper configuration?

You say and so on, is there anything else to be done?

Sorry for all the questions, but there is no comments around the logic of the structures and also no documentations on this, I found nothing else in the issues of this repo, no clues in most of the forks I have checked out.
