### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by taoye1996** [awni/ecg#24]
I use python3.6 to run the example of cinc17.  When I run the code 'python ecg/train.py examples/cinc17/config.json -e cinc17' in 'README', I got this error:
 
$ python ecg/train.py examples/cinc17/config.json -e cinc17
Loading training set...
Using TensorFlow backend.
Traceback (most recent call last):
  File "ecg/train.py", line 93, in <module>
    train(args, params)
  File "ecg/train.py", line 33, in train
    train = load.load_dataset(params['train'])
  File "C:\Users\Administrator\ecg\ecg\load.py", line 65, in load_dataset
    with open(data_json, 'r') as fid:
PermissionError: [Errno 13] Permission denied: 'examples/cinc17/data/training2017'

 
Could you please tell me how can I solve this probelm? Thanks a lot.

**Comment by king-no-crown** [comment]
with open(data_json, 'r') as fid:   becomes  with open(data_json, 'rb') as fid:

**Comment by amitjslearn** [comment]
@king-no-crown  @taoye1996  did you use python 2 or python 3 for this project?

**Comment by king-no-crown** [comment]
When the file was downloaded, there was an Excel file with the four categories corresponding to the heart disease number.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "awni/ecg"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 下午2:30
收件人:&nbsp;"awni/ecg"<ecg@noreply.github.com&gt;;
抄送:&nbsp;"hjl"<929251610@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [awni/ecg] How can I solve this problem? (#24)





 
@king-no-crown  @taoye1996  did you use python 2 or python 3 for this project?
